# Combining Datasets: Concat and Append

Some of the most interesting studies of data come from combining different data sources.
These operations can involve anything from very straightforward concatenation of two different datasets, to more complicated database-style joins and merges that correctly handle any overlaps between the datasets.
``Series`` and ``DataFrame``s are built with this type of operation in mind, and Pandas includes functions and methods that make this sort of data wrangling fast and straightforward.

Here we'll take a look at simple concatenation of ``Series`` and ``DataFrame``s with the ``pd.concat`` function; later we'll dive into more sophisticated in-memory merges and joins implemented in Pandas.

We begin with the standard imports:

In [1]:
import pandas as pd
import numpy as np

## Recall: Concatenation of NumPy Arrays

Concatenation of ``Series`` and ``DataFrame`` objects is very similar to concatenation of Numpy arrays, which can be done via the ``np.concatenate`` function.

In [2]:
x = [1, 2, 3]
y = [4, 5, 6]
z = [7, 8, 9]
np.concatenate([x, y, z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.concatenate([x, y, z],axis=0)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.concatenate([x, y, z],axis=1)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

The first argument is a list or tuple of arrays to concatenate.
Additionally, it takes an ``axis`` keyword that allows you to specify the axis along which the result will be concatenated:

In [7]:
x = [[1, 2],
     [3, 4]]
x = [[1, 2],
     [3, 4]]
np.concatenate([x, x], axis=0) # add more row

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

It specifies the ``axis`` along which the means are computed. By default axis=0. This is consistent with the numpy.mean usage when axis is specified explicitly (in numpy.mean, axis==None by default, which computes the mean value over the flattened array) , in which axis=0 along the rows (namely, index in pandas), and axis=1 along the columns. For added clarity, one may choose to specify axis='index' (instead of axis=0) or axis='columns' (instead of axis=1).

In [8]:
x = [[1, 2],
     [3, 4]]
np.concatenate([x, x], axis=1) # add more columns

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

## Simple Concatenation with ``pd.concat``

Pandas has a function, ``pd.concat()``, which has a similar syntax to ``np.concatenate`` but contains a number of options that we'll discuss momentarily:

```python
# Signature in Pandas v0.18
pd.concat(objs, axis=0, join='outer', join_axes=None, ignore_index=False,
          keys=None, levels=None, names=None, verify_integrity=False,
          copy=True)
```

``pd.concat()`` can be used for a simple concatenation of ``Series`` or ``DataFrame`` objects, just as ``np.concatenate()`` can be used for simple concatenations of arrays:

In [9]:
ser1 = pd.Series(['A', 'B', 'C'], index=[1, 2, 3])
ser2 = pd.Series(['D', 'E', 'F'], index=[4, 5, 6])


In [10]:
ser1

1    A
2    B
3    C
dtype: object

In [11]:
ser2

4    D
5    E
6    F
dtype: object

In [12]:
pd.concat([ser1, ser2])

1    A
2    B
3    C
4    D
5    E
6    F
dtype: object

It also works to concatenate higher-dimensional objects, such as ``DataFrame``s:

In [13]:
def make_df(cols, ind):
    """Quickly make a DataFrame"""
    data = {c: [str(c) + str(i) for i in ind]
            for c in cols}
    return pd.DataFrame(data, ind)

# example DataFrame
make_df('ABC', range(3))

A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [14]:
df1 = make_df('AB', [1, 2])
df2 = make_df('AB', [3, 4])
df1

A   B
1  A1  B1
2  A2  B2

In [15]:
df2

A   B
3  A3  B3
4  A4  B4

In [16]:
pd.concat([df1, df2])

A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4

By default, the concatenation takes place row-wise within the ``DataFrame`` (i.e., ``axis=0``).
Like ``np.concatenate``, ``pd.concat`` allows specification of an axis along which concatenation will take place.
Consider the following example:

In [17]:
df3 = make_df('AB', [0, 1])
df4 = make_df('CD', [0, 1])
df3

A   B
0  A0  B0
1  A1  B1

In [18]:
df4

C   D
0  C0  D0
1  C1  D1

In [19]:
pd.concat([df3, df4], axis=1)

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1

We could have equivalently specified ``axis=1``; here we've used the more intuitive ``axis='col'``. 

### Duplicate indices

One important difference between ``np.concatenate`` and ``pd.concat`` is that Pandas concatenation *preserves indices*, even if the result will have duplicate indices!
Consider this simple example:

In [20]:
x = make_df('AB', [0, 1])
y = make_df('AB', [2, 3])
y.index = x.index  # make duplicate indices!
x

A   B
0  A0  B0
1  A1  B1

In [21]:
y

A   B
0  A2  B2
1  A3  B3

In [22]:
pd.concat([x, y],axis='rows')

A   B
0  A0  B0
1  A1  B1
0  A2  B2
1  A3  B3

In [23]:
pd.concat([x, y],axis=1)

A   B   A   B
0  A0  B0  A2  B2
1  A1  B1  A3  B3

# Combining Datasets: Merge and Join

One essential feature offered by Pandas is its high-performance, in-memory join and merge operations.
If you have ever worked with databases, you should be familiar with this type of data interaction.
The main interface for this is the ``pd.merge`` function, and we'll see few examples of how this can work in practice.


## Relational Algebra

The behavior implemented in ``pd.merge()`` is a subset of what is known as *relational algebra*, which is a formal set of rules for manipulating relational data, and forms the conceptual foundation of operations available in most databases.
The strength of the relational algebra approach is that it proposes several primitive operations, which become the building blocks of more complicated operations on any dataset.
With this lexicon of fundamental operations implemented efficiently in a database or other program, a wide range of fairly complicated composite operations can be performed.

Pandas implements several of these fundamental building-blocks in the ``pd.merge()`` function and the related ``join()`` method of ``Series`` and ``Dataframe``s.
As we will see, these let you efficiently link data from different sources.

## Categories of Joins

The ``pd.merge()`` function implements a number of types of joins: the *one-to-one*, *many-to-one*, and *many-to-many* joins.
All three types of joins are accessed via an identical call to the ``pd.merge()`` interface; the type of join performed depends on the form of the input data.
Here we will show simple examples of the three types of merges, and discuss detailed options further below.

### One-to-one joins

Perhaps the simplest type of merge expresion is the one-to-one join, which is in many ways very similar to the column-wise concatenation
As a concrete example, consider the following two ``DataFrames`` which contain information on several employees in a company:

In [24]:
df1 = pd.DataFrame({'employee': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'group': ['Accounting', 'Engineering', 'Engineering', 'HR']})
df2 = pd.DataFrame({'employee': ['Lisa', 'Bob', 'Jake', 'Sue'],
                    'hire_date': [2004, 2008, 2012, 2014]})
df1

employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR

In [25]:
df2

employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014

To combine this information into a single ``DataFrame``, we can use the ``pd.merge()`` function:

In [26]:
df3 = pd.merge(df2, df1)
df3

employee  hire_date        group
0     Lisa       2004  Engineering
1      Bob       2008   Accounting
2     Jake       2012  Engineering
3      Sue       2014           HR

The ``pd.merge()`` function recognizes that each ``DataFrame`` has an "employee" column, and automatically joins using this column as a key.
The result of the merge is a new ``DataFrame`` that combines the information from the two inputs.
Notice that the order of entries in each column is not necessarily maintained: in this case, the order of the "employee" column differs between ``df1`` and ``df2``, and the ``pd.merge()`` function correctly accounts for this.
Additionally, keep in mind that the merge in general discards the index, except in the special case of merges by index (see the ``left_index`` and ``right_index`` keywords, discussed momentarily).

### Many-to-one joins

Many-to-one joins are joins in which one of the two key columns contains duplicate entries.
For the many-to-one case, the resulting ``DataFrame`` will preserve those duplicate entries as appropriate.
Consider the following example of a many-to-one join:

In [27]:
df4 = pd.DataFrame({'group': ['Accounting', 'Engineering', 'HR'],
                    'supervisor': ['Carly', 'Guido', 'Steve']})
df4

group supervisor
0   Accounting      Carly
1  Engineering      Guido
2           HR      Steve

In [28]:
df3

employee  hire_date        group
0     Lisa       2004  Engineering
1      Bob       2008   Accounting
2     Jake       2012  Engineering
3      Sue       2014           HR

In [29]:
df6 = pd.merge(df3, df4)
df6

employee  hire_date        group supervisor
0     Lisa       2004  Engineering      Guido
1      Bob       2008   Accounting      Carly
2     Jake       2012  Engineering      Guido
3      Sue       2014           HR      Steve

The resulting ``DataFrame`` has an aditional column with the "supervisor" information, where the information is repeated in one or more locations as required by the inputs.

### Many-to-many joins

Many-to-many joins are a bit confusing conceptually, but are nevertheless well defined.
If the key column in both the left and right array contains duplicates, then the result is a many-to-many merge.
This will be perhaps most clear with a concrete example.
Consider the following, where we have a ``DataFrame`` showing one or more skills associated with a particular group.
By performing a many-to-many join, we can recover the skills associated with any individual person:

In [30]:
df5 = pd.DataFrame({'group': ['Accounting', 'Accounting',
                              'Engineering', 'Engineering', 'HR', 'HR'],
                    'skills': ['math', 'spreadsheets', 'coding', 'linux',
                               'spreadsheets', 'organization']})
df5

group        skills
0   Accounting          math
1   Accounting  spreadsheets
2  Engineering        coding
3  Engineering         linux
4           HR  spreadsheets
5           HR  organization

In [31]:
df1

employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR

In [32]:
pd.merge(df1, df5)

employee        group        skills
0      Bob   Accounting          math
1      Bob   Accounting  spreadsheets
2     Jake  Engineering        coding
3     Jake  Engineering         linux
4     Lisa  Engineering        coding
5     Lisa  Engineering         linux
6      Sue           HR  spreadsheets
7      Sue           HR  organization

In [33]:
pd.merge(df6, df5)

employee  hire_date        group supervisor        skills
0     Lisa       2004  Engineering      Guido        coding
1     Lisa       2004  Engineering      Guido         linux
2      Bob       2008   Accounting      Carly          math
3      Bob       2008   Accounting      Carly  spreadsheets
4     Jake       2012  Engineering      Guido        coding
5     Jake       2012  Engineering      Guido         linux
6      Sue       2014           HR      Steve  spreadsheets
7      Sue       2014           HR      Steve  organization

In [34]:
pd.merge(df5, df6)

group        skills employee  hire_date supervisor
0   Accounting          math      Bob       2008      Carly
1   Accounting  spreadsheets      Bob       2008      Carly
2  Engineering        coding     Lisa       2004      Guido
3  Engineering        coding     Jake       2012      Guido
4  Engineering         linux     Lisa       2004      Guido
5  Engineering         linux     Jake       2012      Guido
6           HR  spreadsheets      Sue       2014      Steve
7           HR  organization      Sue       2014      Steve

### Practice 

You are given two CSV files:

**students.csv**

| Student_ID | Name     | Major             |
|------------|----------|------------------|
| 1001       | Alice    | Computer Science |
| 1002       | Bob      | Math             |
| 1003       | Charlie  | Physics          |
| 1004       | Diana    | Economics        |

**scores.csv**

| Student_ID | Course    | Score |
|------------|-----------|-------|
| 1001       | CS101     | 95    |
| 1002       | MATH201   | 88    |
| 1003       | PHY111    | 72    |
| 1005       | BIO150    | 85    |

 🎯 **Tasks**

1. **Fill data** into pandas DataFrames.  
2. **Merge the DataFrames** on `Student_ID` using:
   - Inner join → keep only students present in both datasets.  
   - Left join → keep all students from `students.csv`, with matching scores where available.  
3. After each join, **print the resulting DataFrame** and explain the difference in the number of rows.  
4. Rename the `Score` column to `Final_Score` in the merged DataFrame.  
5. Save the final **outer join result** as `merged_results.csv`.

In [35]:
df = pd.DataFrame({'Student_ID': [1001, 1002, 1003, 1004],
                   'Name': ['Alice', 'Bob', 'Charlie', 'Diana'],
                   'Major': ['Computer Science', 'Math', 'Physics', 'Economics']})
df2 = pd.DataFrame({'Student_ID': [1001, 1002, 1003, 1005],
                   'Course': ['CS101', 'MATH201', 'PHY111', 'BIO150'],
                   'Score': [95, 88, 72, 85]})

In [36]:
inner_result = pd.merge(df, df2, on='Student_ID', how='inner')
left_result = pd.merge(df, df2, on='Student_ID', how='left')
inner_result

Student_ID     Name             Major   Course  Score
0        1001    Alice  Computer Science    CS101     95
1        1002      Bob              Math  MATH201     88
2        1003  Charlie           Physics   PHY111     72

In [37]:
left_result


Student_ID     Name             Major   Course  Score
0        1001    Alice  Computer Science    CS101   95.0
1        1002      Bob              Math  MATH201   88.0
2        1003  Charlie           Physics   PHY111   72.0
3        1004    Diana         Economics      NaN    NaN

**An inner merge** excludes the student with student_id 1004 because that student does not exist in both DataFrames. In contrast, a **left merge** includes all students from the left DataFrame, and for the student_id 1004 that has no match in the right DataFrame, it shows NaN values for the columns from the right side.


In [38]:
# Perform an outer merge
outer_result = pd.merge(df, df2, on='Student_ID', how='outer')

# Rename 'Score' to 'Final_Score'
outer_result = outer_result.rename(columns={'Score': 'Final_Score'})

# Save the final outer join result
outer_result.to_csv('merged_results.csv', index=False)